version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jarlinandresfb
      - MONGO_INITDB_ROOT_PASSWORD=Prueba123.
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db