server:
  port: 8081
spring:
  application:
    name: "db-creator"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://dummy.restapiexample.com/api/v1"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
